import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const agency = localFont({
  src: '../fonts/agency/agency.ttf',
  variable: '--font-agency',
  display: 'swap'
});

const alegreyaSans = localFont({
  src: [
    {
      path: '../fonts/alegreya/alegreyasans-regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../fonts/alegreya/alegreyasans-italic.ttf',
      weight: '400',
      style: 'italic'
    },
    {
      path: '../fonts/alegreya/alegreyasans-bold.ttf',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../fonts/alegreya/alegreyasans-bolditalic.ttf',
      weight: '700',
      style: 'italic'
    }
  ],
  variable: '--font-alegreya',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const finalClassName = `${agency.variable} ${alegreyaSans.variable}`;
  return (
    <html lang="en" className={finalClassName}>
      <body >{children}</body>
    </html>
  );
}
